export const projectsData = [
  {
    name: "Intelligent Real-Time PPE Monitoring & Alert System",
    category: "Computer Vision + AI-IoT",
    description: "Graduation project connecting YOLOv8 PPE detection with a Node.js/Express backend, MongoDB, MQTT, Socket.IO, a React supervisor dashboard, and a Flutter worker-alert app.",
    github_link: "",
    demo: "",
    tech: ["YOLOv8", "Python", "OpenCV", "Node.js", "Flutter"],
    image: "/projects/ppe-monitor.png",
  },
  {
    name: "SomWay Travel & Logistics",
    category: "Business Operations",
    description: "Operator workspace for ticketing, bookings, cargo, visa services, client records, receivables, receipts, and branch-aware operations.",
    github_link: "",
    demo: "",
    tech: ["Operations", "Cargo", "Bookings", "Receivables"],
    image: "/projects/somway-dashboard.png",
  },
  {
    name: "Curdun Cargo Management System",
    category: "Logistics Platform",
    description: "Multi-role cargo platform covering container intake, Bill of Lading details, warehouse stock, inter-branch transfers, drivers, trips, and reporting.",
    github_link: "",
    demo: "",
    tech: ["Cargo", "Warehouse", "Transfers", "Reports"],
    image: "/projects/curdun-warehouse.png",
  },
  {
    name: "Pediatric Health Hub",
    category: "Healthcare Platform",
    description: "Multi-portal pediatric-care platform connecting parents, doctors, facilities, and administrators through appointments, AI guidance, records, and browser-based teleconsultation.",
    github_link: "https://github.com/Sharmasheeno/pediatric-health-hub",
    demo: "",
    tech: ["React", "Node.js", "Prisma", "MySQL"],
    image: "/projects/pediatric-parent.jpeg",
  },
  {
    name: "CyberSentinel Hybrid Malware Detection Platform",
    category: "Cybersecurity + Machine Learning",
    description: "Incident-response suite combining React/Vite, Node.js/Express, MongoDB, Socket.IO, and a Python/Flask Random Forest service for PE analysis, phishing investigation, and suspicious-email sanitization.",
    github_link: "https://github.com/Sharmasheeno/CyberSentinel---Hybrid-Malware-Detection-Platform",
    demo: "",
    tech: ["Python", "Flask", "scikit-learn", "React", "Node.js"],
    image: "/projects/cybersentinel-forensic.png",
  },
  {
    name: "SOM Election Platform",
    category: "Civic Technology",
    description: "Electronic voting platform with public candidate profiles, protected voter workflows, administrator controls, JWT authentication, and a MySQL/Sequelize data layer.",
    github_link: "https://github.com/Sharmasheeno/som-election-platform",
    demo: "",
    tech: ["React", "Node.js", "Express", "MySQL"],
    image: "/projects/election-voter.jpeg",
  },
  {
    name: "SleepMetrics - Sleep Quality Predictor",
    category: "Machine Learning + Full Stack",
    description: "Three-tier application that sends health and biometric inputs through a React/Tailwind UI, Node.js/Express and MongoDB API, and a Python/Flask Random Forest prediction service.",
    github_link: "https://github.com/Sharmasheeno/Sleepmatrics",
    demo: "",
    tech: ["React", "Node.js", "MongoDB", "Python", "Flask"],
    image: "/projects/sleepmetrics-result.jpeg",
  },
];
